create database QLBH_Nhom4

use QLBH_Nhom4

create table KHACHHANG
(
MAKH INT IDENTITY(01,1) PRIMARY KEY,  
TENKH VARCHAR(40),
NGSINH SMALLDATETIME,
GIOITINH VARCHAR(5),
SDTKH VARCHAR(10),
DOANHSO INT
)

ALTER TABLE KHACHHANG ALTER COLUMN TENKH NVARCHAR(50)
ALTER TABLE KHACHHANG ALTER COLUMN GIOITINH NVARCHAR(10)

ALTER TABLE KHACHHANG ADD CONSTRAINT
CHK_GIOITINH CHECK(GIOITINH = 'Nam' OR GIOITINH = 'Nu')
ALTER TABLE KHACHHANG DROP CONSTRAINT CHK_GIOITINH 

CREATE TABLE SANPHAM
(
MASP INT IDENTITY(01,1) PRIMARY KEY,
TENSP VARCHAR(40),
GIA MONEY,
MALOAISP INT
)
ALTER TABLE SANPHAM ALTER COLUMN TENSP NVARCHAR(50)

ALTER TABLE SANPHAM ADD CONSTRAINT
FK_LOAISP_SP FOREIGN KEY (MALOAISP) REFERENCES LOAISP(MALOAISP)

CREATE TABLE LOAISP
(
MALOAISP INT IDENTITY(01,1) PRIMARY KEY,
TENLOAISP VARCHAR(40)
)
ALTER TABLE LOAISP ALTER COLUMN TENLOAISP NVARCHAR(50)
CREATE TABLE NHANVIEN
(
MANV INT IDENTITY(01,1) PRIMARY KEY,
TENNV VARCHAR(40),
SDTNV VARCHAR(10),
LUONG MONEY
)
ALTER TABLE NHANVIEN ALTER COLUMN TENNV NVARCHAR(50)
ALTER TABLE NHANVIEN ALTER COLUMN GIOITINH NVARCHAR(10)
CREATE TABLE HOADON
(
SOHD INT IDENTITY(01,1) PRIMARY KEY,
NGHD SMALLDATETIME,
TRIGA MONEY,
MAKH INT FOREIGN KEY REFERENCES KHACHHANG(MAKH),
MANV INT FOREIGN KEY REFERENCES NHANVIEN(MANV)
)

CREATE TABLE CTHD 
(
SOHD INT FOREIGN KEY REFERENCES HOADON(SOHD),
MASP INT FOREIGN KEY REFERENCES SANPHAM(MASP),
SOLUONG INT
)

ALTER TABLE SANPHAM ADD SOLUONGSP INT CHECK (SOLUONGSP >= 0)

CREATE TABLE ACCOUNT
(
MATK INT IDENTITY(01,1) PRIMARY KEY,
MANV INT FOREIGN KEY REFERENCES NHANVIEN(MANV),
EMAIL VARCHAR(40),
TAIKHOAN VARCHAR(50),
MATKHAU VARCHAR(50) 
)

CREATE TABLE KHUYENMAI
(
 MAKM INT IDENTITY(01,1) PRIMARY KEY,
 MAKH INT FOREIGN KEY REFERENCES KHACHHANG(MAKH),
 GIATRIKM INT CHECK (GIATRIKM IN (5,20,30)),
)

ALTER TABLE SANPHAM ADD NGAYTHEM SMALLDATETIME 
ALTER TABLE NHANVIEN ADD GIOITINH VARCHAR(10) CHECK (GIOITINH IN ('Nam','Nữ'))
ALTER TABLE NHANVIEN ADD NGSINH SMALLDATETIME CHECK ( YEAR(NGSINH) - YEAR(GETDATE()) >= 18 )
 
 INSERT NHANVIEN (TENNV,NGSINH,GIOITINH,SDTNV,LUONG) VALUES (N'thịnh vũ','6/2/2002',N'nam',123456,123456)
 INSERT NHANVIEN (TENNV,NGSINH,GIOITINH,SDTNV,LUONG) VALUES (N'thhf ','7/14/2021',N'Nam',3452,234)
 INSERT NHANVIEN (TENNV,NGSINH,GIOITINH,SDTNV,LUONG) VALUES (N'greg','12/6/2022',N'Nữ',45,45)

 CREATE PROCEDURE NhanVienSelect
 AS 
 SELECT * FROM NHANVIEN
 GO

 CREATE PROCEDURE KhachHangSelect
 AS
 SELECT * FROM KHACHHANG  
 GO

 CREATE PROCEDURE SanPhamSelect
 AS
 SELECT * FROM SANPHAM
 GO

 CREATE PROCEDURE CTHDSelect
 AS
 SELECT * FROM CTHD
 GO

 CREATE PROCEDURE LoaiSanPhamSelect
 AS
 SELECT * FROM LOAISP
 GO

 CREATE PROCEDURE HoaDonSelect
 AS
 SELECT * FROM HOADON
 GO


 EXEC  HoaDonSelect

 EXEC LoaiSanPhamSelect

 EXEC NhanVienSelect

 EXEC KhachHangSelect

 EXEC SanPhamSelect

 EXEC CTHDSelect

alter table NHANVIEN DROP CONSTRAINT CK__NHANVIEN__NGSINH__36B12243

alter table NHANVIEN drop constraint CK__NHANVIEN__GIOITI__35BCFE0A

alter table NHANVIEN ADD FILEANH VARCHAR(50);

INSERT KHACHHANG VALUES (N'efgerg','12/16/2022',N'Nữ',123,234)
INSERT KHACHHANG VALUES (N'RETRET45','12/20/2022',N'Nam',345,345)
INSERT KHACHHANG VALUES (N'erf','12/20/2020',N'Nam',345,345)
ALTER TABLE KHACHHANG ADD FILEANH VARCHAR(50)
alter table NHANVIEN DROP COLUMN FILEANH

INSERT SANPHAM VALUES (N'trergregh',56,0,5,'12/13/2022')

alter table LOAISP add unique(TENLOAISP)

select MALOAISP from LOAISP WHERE TENLOAISP =N'Dụng cụ học tập'

select * from HOADON
select * from CTHD
from LOAISP LSP,SANPHAM SP
where LSP.MALOAISP = SP.MALOAISP

select * FROM HOADON
SELECT GIA FROM SANPHAM WHERE MASP = 4
select * from CTHD
SELECT GIA FROM SANPHAM WHERE MASP = 4

SELECT MAX(SOHD) AS SOHOADON FROM HOADON

SELECT * FROM HOADON HD,CTHD CT WHERE HD.SOHD = CT.SOHD

SELECT * FROM ACCOUNT