create database QLBH_Nhom4

use QLBH_Nhom4

create table KHACHHANG
(
MAKH INT IDENTITY(01,1) PRIMARY KEY,
TENKH VARCHAR(40),
NGSINH SMALLDATETIME,
GIOITINH VARCHAR(5),
SDTKH VARCHAR(10),
DOANHSO INT
)

ALTER TABLE KHACHHANG ADD CONSTRAINT
CHK_GIOITINH CHECK(GIOITINH = 'Nam' OR GIOITINH = 'Nu')

CREATE TABLE SANPHAM
(
MASP INT IDENTITY(01,1) PRIMARY KEY,
TENSP VARCHAR(40),
GIA MONEY,
MALOAISP INT
)

ALTER TABLE SANPHAM ADD CONSTRAINT
FK_LOAISP_SP FOREIGN KEY (MALOAISP) REFERENCES LOAISP(MALOAISP)

CREATE TABLE LOAISP
(
MALOAISP INT IDENTITY(01,1) PRIMARY KEY,
TENLOAISP VARCHAR(40)
)

CREATE TABLE NHANVIEN
(
MANV INT IDENTITY(01,1) PRIMARY KEY,
TENNV VARCHAR(40),
SDTNV VARCHAR(10),
LUONG MONEY
)

CREATE TABLE HOADON
(
SOHD INT IDENTITY(01,1) PRIMARY KEY,
NGHD SMALLDATETIME,
TRIGA MONEY,
MAKH INT FOREIGN KEY REFERENCES KHACHHANG(MAKH),
MANV INT FOREIGN KEY REFERENCES NHANVIEN(MANV)
)

CREATE TABLE CTHD 
(
SOHD INT FOREIGN KEY REFERENCES HOADON(SOHD),
MASP INT FOREIGN KEY REFERENCES SANPHAM(MASP),
SOLUONG INT
)

ALTER TABLE SANPHAM ADD SOLUONGSP INT CHECK (SOLUONGSP >= 0)

CREATE TABLE ACCOUNT
(
MATK INT IDENTITY(01,1) PRIMARY KEY,
MANV INT FOREIGN KEY REFERENCES NHANVIEN(MANV),
EMAIL VARCHAR(40),
TAIKHOAN VARCHAR(50),
MATKHAU VARCHAR(50) 
)

CREATE TABLE KHUYENMAI
(
 MAKM INT IDENTITY(01,1) PRIMARY KEY,
 MAKH INT FOREIGN KEY REFERENCES KHACHHANG(MAKH),
 GIATRIKM INT CHECK (GIATRIKM IN (5,20,30)),
)

ALTER TABLE SANPHAM ADD NGAYTHEM SMALLDATETIME 
ALTER TABLE NHANVIEN ADD GIOITINH VARCHAR(10) CHECK (GIOITINH IN ('NAM','NU'))
ALTER TABLE NHANVIEN ADD NGSINH SMALLDATETIME CHECK ( YEAR(NGSINH) - YEAR(GETDATE()) >= 18 )
 



